spring.application.name=product-api

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/eadp_product_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ijse@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


accessKey=TEST_ACCESS_KEY_123456789
secretKey=TEST_SECRET_KEY_123456789
bucketName=test-bucket-local-only
region=ap-south-1

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


